### ISSUE TITLE
Redirect URI defaults to localhost instead of custom domain

### ISSUE THREAD

**Issue by zeandrade** [fedora-infra/flask-oidc#130]
Hi everyone,

I’m using Flask-OIDC with Gunicorn and NGINX (serving on an intranet domain like https://myapp.local) alongside Keycloak as the IdP. My configuration looks something like this:

https://myapp.local ⟶ https://mykeycloak.local
(All using HTTPS with certificates issued by an internal Certificate Authority (CA), which are functioning correctly).

However, the redirect_uri consistently defaults to http://localhost:PORT regardless of my settings, resulting in an invalid_request error on Keycloak. When I set OIDC_OVERWRITE_REDIRECT_URI, Keycloak recognizes the redirect_uri correctly, but this leads to a redirect loop after authentication. It appears that values from client_secrets.json or environment variables are ignored.

I’m not fully familiar with OIDC, but from what I understand, it seems request.url_root may be influencing the redirect_uri (and the "next" parameter) in my setup.

Is there a way to configure "https://myapp.local" as the redirect_uri, as expected by Keycloak, while avoiding the redirect loop after authentication?

from  Flask-OIDC  views.py 
```python
def login_view():
    if current_app.config["OIDC_OVERWRITE_REDIRECT_URI"]:
        redirect_uri = current_app.config["OIDC_OVERWRITE_REDIRECT_URI"]
    elif current_app.config["OIDC_CALLBACK_ROUTE"]:
        redirect_uri = (
            f"{request.url_root.rstrip('/')}{current_app.config['OIDC_CALLBACK_ROUTE']}"
        )
    else:
        redirect_uri = url_for("oidc_auth.authorize", _external=True)
    session["next"] = request.args.get("next", request.url_root)
    before_login_redirect.send(
        g._oidc_auth,
        redirect_uri=redirect_uri,
        next=session["next"],
    )
    return g._oidc_auth.authorize_redirect(redirect_uri)
    ```

**Comment by abompard** [comment]
Hi! It may come from your proxy config actually, do you have the same `proxy_set_header` lines as here:
https://docs.gunicorn.org/en/stable/deploy.html ?
Nginx must be instructed to forward requests while preserving the `Host` header, otherwise gunicorn will see request aimed at `localhost` and Flask will not generate URLs appropriately.

**Comment by zeandrade** [comment]
Hi @abompard , 
 Thanks for the tips, THAT's IT!
Original settings  looks like this:
 ```nginx 
location / {
            client_max_body_size 16M;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_set_header        X-Forwarded-Host $host;
            proxy_pass http://localhost:8084/;
        }
```
        
 Gunicorn run this:       
        
```bash
gunicorn --workers 3 --bind localhost:8084 main:app
```

I add   `proxy_set_header Host $http_host;`  and now everything is working!!

```
location / {
            client_max_body_size 16M;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_set_header        X-Forwarded-Host $host;
            proxy_set_header Host $http_host;
            proxy_pass http://localhost:8084/;
        }
        
```
