### ISSUE TITLE
Migrate Pagure's OIDC support to this new version of flask-oidc

### ISSUE THREAD

**Issue by gridhead** [fedora-infra/flask-oidc#137]
It seems to work with this set of packages: https://abompard.fedorapeople.org/flask-oidc-el6/

**Comment by gridhead** [comment]
A scheduled downtime was announced for Pagure & Dist Git's migration to OIDC https://pagure.io/fedora-infrastructure/issue/12272 and https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/ZT2JWP3UNUFRKQYTDCEVEADJAAF5F7ME/. 

Pagure has been migrated to the most recent version of `python-flask-oidc` available on the RHEL8 Infrastructure tag, specifically `2.2.0`, with `python-authlib` version `1.3.1`. The same was attempted on the staging Dist Git, but it needs further investigation before making an informed decision, and hence, a separate downtime will be announced for it.

**Comment by AdamWill** [comment]
This probably caused https://pagure.io/fedora-infrastructure/issue/12291 ?
