### ISSUE TITLE
Ensure CPE initiative ticket which maps to this work is updated/closed as a final step in this project

### ISSUE THREAD

**Issue by davidkirwan** [fedora-infra/flask-oidc#2]
# Story Time

As a developer, I want to ensure that the corresponding ticket in fedora-infra which maps to this work gets closed so that the community is aware the work has been completed.

# Tasks

- As a final step, please update and close the fedora-infra ticket which maps to this work: https://pagure.io/cpe/initiatives-proposal/issue/19
- Need to follow up with another similar ticket to ensure flask-oidc is still working at the end of this project https://pagure.io/pagure/issue/5288

# Success Criteria
- Work is completed

**Comment by abompard** [comment]
Hey, what's the status of that @davidkirwan ?

**Comment by davidkirwan** [comment]
https://pagure.io/cpe/initiatives-proposal/issue/19 is closed few days back, can close I'd say.
