### ISSUE TITLE
Update Flask-OIDC itsdangerous to authlib 1.0.1

### ISSUE THREAD

**Issue by james02135** [fedora-infra/flask-oidc#4]
# itsdangerous JSONWEBSignatureSerializer is deprecated since version 2.0.0. Flask OIDC uses this in the __init__.py file which needs to be refactored to use Authlib

# Tasks

- include authlib as a dependency
- import authlib into the __init__.py file
- change any functions that use the old itsdangerous call

# Success Criteria
- File successfully runs

**Comment by davidkirwan** [comment]
We've replaced the JSONWebSignatureSerializer functionality from `itsdangerous` with an implementation which uses a similar function provided by authlib.
