### ISSUE TITLE
OVERWRITE_REDIRECT_URI use case

### ISSUE THREAD

**Issue by willthetanman** [fedora-infra/flask-oidc#43]
Hello @abompard previously it was mentioned in https://github.com/fedora-infra/flask-oidc/issues/21 that my use case for OVERWRITE_REDIRECT_URI was solely for https redirection, however this was incorrect. 

Because we are using Gunicorn `SCRIPT_NAME` feature to proxy multiple Flask apps depending on the URI set, not being able to force a redirect URI to our specific application after OIDC auth flow is causing our flow to 'break' and return 404. 

**Example set up for multiple apps proxied** 

```
gunicorn --workers 1
    --threads 4 --bind 0.0.0.0:5000 --env SCRIPT_NAME=/application1
    
gunicorn --workers 1
    --threads 4 --bind 0.0.0.0:5000 --env SCRIPT_NAME=/application2
```
       

We would set OVERWRITE_REDIRECT_URI=https://myapp.com/application1, so after the OIDC flow it will redirect to https://myapp.com/application1. However as of `2.0.3` it would redirect to https://myapp.com instead after completed login since OVERWRITE_REDIRECT_URI is no longer supported.

**Comment by abompard** [comment]
Thanks for getting back to me with this.
The `OVERWRITE_REDIRECT_URI` option will be restored with the `OIDC_` prefix by PR #37.

**Comment by willthetanman** [comment]
Thank you so much!
