### ISSUE TITLE
Infinite 302 redirect for /logout?reason=expired

### ISSUE THREAD

**Issue by willthetanman** [fedora-infra/flask-oidc#52]
We are noticing an occasion issue that is difficult to reproduce where our app gets stuck in an infinite 302 redirect to `/logout?reason=expired`. Clearing the cookies will usually fix the problem however issue presents itself again after indeterminate amount of time.

Below are the areas I think may be causing the issue but have not throughly investigated. 

https://github.com/fedora-infra/flask-oidc/blob/develop/flask_oidc/__init__.py#L212
https://github.com/fedora-infra/flask-oidc/blob/develop/tests/test_views.py#L55

<img width="1114" alt="Screenshot 2023-10-26 at 12 22 18 PM" src="https://github.com/fedora-infra/flask-oidc/assets/4429499/801aa708-a0cc-4e0b-93a6-6b61851f77e0">
<img width="1575" alt="Screenshot 2023-10-26 at 12 18 51 PM" src="https://github.com/fedora-infra/flask-oidc/assets/4429499/732f16c7-44c1-4dfc-a1c3-590899e2827e">

**Comment by abompard** [comment]
Thanks for reporting! I think I found the issue, I'm betting your Flask server is not mounted on the root of the webserver. The logout loop guard was not checking for this, I've pushed a commit that checks it.
I'll cut a new release shortly.

**Comment by willthetanman** [comment]
Yes! that is likely the issue as we don't run on root but instead eg. https://basedomain.com/application1/. I will test this, thank you for rapid response.
