### ISSUE TITLE
OIDC_CALLBACK_ROUTE isn't relative to app root

### ISSUE THREAD

**Issue by russau** [fedora-infra/flask-oidc#63]
`OIDC_CALLBACK_ROUTE` is deprecated so I don't know if there's active dev on the feature.  Anyways, here's something I just spotted.  URLs are getting built that don't consider an application root.

If I configure a `OIDC_CALLBACK_ROUTE` of `/authorization-code/callback`.  In `views.py` a redirect URL of `"https://mysite.dev/authorization-code/callback"` is getting built.  But my site is hosted under a prefix of `/banana`. So users are redirected to a route that doesn't exist on my site.

https://github.com/fedora-infra/flask-oidc/blob/bd1dd97c79f31142b92600b2ae4ce97744a860ff/flask_oidc/views.py#L35

If I update the `OIDC_CALLBACK_ROUTE` to include the  `root_path`, i.e. `/banana/authorization-code/callback`. Then the code below is used to configure the route doesn't work because it shouldn't include the prefix.

https://github.com/fedora-infra/flask-oidc/blob/bd1dd97c79f31142b92600b2ae4ce97744a860ff/flask_oidc/__init__.py#L162-L163

I think it could be fixed by building the URL using `request.url_root` (would need something to do the switch to https also), i.e.:

```
redirect_uri = (
    f`{request.url_root}{current_app.config['OIDC_CALLBACK_ROUTE']}"
)
```

**Comment by abompard** [comment]
Hi! Could you try with a more recent version of flask-oidc? I think it's handled now.
