### ISSUE TITLE
Is this the new upstream for flask-oidc?

### ISSUE THREAD

**Issue by praiskup** [fedora-infra/flask-oidc#7]
if yes, can we somehow redirect users from the original Patrick's repo?  At least questions like this https://github.com/puiterwijk/flask-oidc/issues/146 should get answers.

**Comment by siddharthvipul** [comment]
Hey,
This is not exactly the new upstream.
This is mere the working place where @davidkirwan and @james02135 (and I) are experimenting and making changes. Once ready, we will open a PR to the upstream (Patrick's repo). 
I will reply to https://github.com/puiterwijk/flask-oidc/issues/146 as well
thanks for bringing it to our attention
