### ISSUE TITLE
Documentation code uses undefined variable `g`

### ISSUE THREAD

**Issue by joostrijneveld** [fedora-infra/flask-oidc#88]
The README contains the following text fragment:

> A [:class:`~flask_oidc.model.User`](https://github.com/fedora-infra/flask-oidc/issues/new#id7) object is also provided on g.oidc_user, see its API documentation to discover which convenient properties are available. 

However, `g` is never defined.

Similarly, the code snippet uses `g` as if it were a global, but I find no references to it.

```
@app.route('/alt')
def alternative():
    # This uses the user instance at g.oidc_user instead
    if g.oidc_user.logged_in:
        return 'Welcome %s' % g.oidc_user.profile.get('email')
    else
        return 'Not logged in'
```

Where does this variable come from?

**Comment by joostrijneveld** [comment]
It appears this is to be imported from flask, i.e., `from flask import Flask, g, session`

**Comment by GraemeMeyerGT** [comment]
Seems like you figured this out for yourself, but indeed `g` is a Flask object that stores data during an application context/request: https://flask.palletsprojects.com/en/3.0.x/api/#flask.g

https://flask.palletsprojects.com/en/3.0.x/appcontext/

Agree the docs could make this a little clearer. For example in the docs main page, the first mention is:

> A [User](https://flask-oidc.readthedocs.io/en/latest/_source/flask_oidc.model.html#flask_oidc.model.User) object is also provided on g.oidc_user, see its API documentation to discover which convenient properties are available.

I'd suggest this could be improved to:

> A [User](https://flask-oidc.readthedocs.io/en/latest/_source/flask_oidc.model.html#flask_oidc.model.User) object is also provided on *[Flask's `g` object](https://flask.palletsprojects.com/en/3.0.x/api/#flask.g)* as g.oidc_user. See its API documentation to discover which convenient properties are available.

**Comment by joostrijneveld** [comment]
Sounds good to me!
